[tool.ruff]
select = [
    "E",
    "F",
    "B",
    "DJ",
    "C90",
    "S",
    "COM",
    "DTZ",
    "EM",
    "PT",
    "RET",
    "SIM",
    "ARG",
    "PTH",
    "PERF",
    "TD",
]
target-version = "py310" # Change this to match the project
line-length = 100
extend-exclude = ["tests", "/migrations/"]
extend-ignore = ["E402", "RET504", "S101", "DJ012"]
ignore-init-module-imports = true
